### PR TITLE
Fix crash when pos_encoding_mode is passed as int

### PR DESCRIPTION
**Pull request by kaixih**
This PR is to fix this issue caused by https://github.com/flashinfer-ai/flashinfer/commit/85d75ca915e64f664dfc33ea5f52446d279bc2ad
```  
File "/scratch/repo/flashinfer/flashinfer/prefill.py", line 83, in get_fmha_module                                                                                                               pos_encoding_mode.value,                                                                                                                                                                       ^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                                    AttributeError: 'int' object has no attribute 'value' 
```

Update get_fmha_module to expect pos_encoding_mode as an Enum instead of an int; raises error otherwise.

cc @yzh119

### CODE REVIEW

File: flashinfer/prefill.py [hunk 1]
```diff
@@ -2592,7 +2592,7 @@ def plan(
                 kv_indptr.dtype,
                 head_dim_qk,
                 head_dim_vo,
-                PosEncodingMode[pos_encoding_mode].value,
+                PosEncodingMode[pos_encoding_mode],
```
[the remark this answers is not in the document]
Comment (yzh119) [reply flashinfer/prefill.py]: It will fail the backends other than "cutlass".
The fundamental solution should be changing the interface of `get_fmha_module` (accepting `pos_encoding_mode` with int data type instead of `PosEncodingMode`:

```python
@functools.cache
def get_fmha_module(
    dtype_q: torch.dtype,
    dtype_kv: torch.dtype,
    dtype_o: torch.dtype,
    dtype_idx: torch.dtype,
    head_dim_qk: int,
    head_dim_vo: int,
    pos_encoding_mode: int,
    use_sliding_window: bool,
    use_logits_soft_cap: bool,
    use_fp16_qk_reduction: bool = False,
):
```

[the remark this answers is not in the document]
Comment (kaixih) [reply flashinfer/prefill.py]: Yes, you're right. Didn't realized `get_batch_prefill_module` also expects the integer `pos_encoding_mode`. Fixed. PTAL.

**Review by yzh119 — APPROVED** [review]
Thank you for the critical bugfix @kaixih !
