### PR TITLE
fix(jit): GEMM kernels produce NaN under concurrency — missing GDC flags cause PDL synchronization barriers to compile as no-ops

### PR DESCRIPTION
**Pull request by voipmonitor**
## Summary

All CUTLASS GEMM templates use `enablePDL=true` (Programmatic Dependent Launch), but the JIT compilation is missing `-DCUTLASS_ENABLE_GDC_FOR_SM100=1` and `-DCUTLASS_ENABLE_GDC_FOR_SM90=1` compile flags. Without these flags, `wait_on_dependent_grids()` and `launch_dependent_grids()` in CUTLASS `grid_dependency_control.h` compile as **empty no-ops**, eliminating the synchronization barriers needed for safe PDL execution.

## Root Cause

In `cutlass/include/cutlass/arch/grid_dependency_control.h`:

```cpp
CUTLASS_DEVICE void wait_on_dependent_grids() {
#if (defined(CUTLASS_GDC_ENABLED))  // only defined when CUTLASS_ENABLE_GDC_FOR_SM100 is set
  asm volatile("griddepcontrol.wait;");
#endif
}
```

The `CUTLASS_GDC_ENABLED` macro is only defined when `CUTLASS_ENABLE_GDC_FOR_SM100` is passed as a compile flag. Without it, PDL launches kernels with overlap enabled at the host level (`cudaLaunchAttributeProgrammaticStreamSerialization`), but the device-side synchronization barriers are compiled out — creating a race condition.

## Symptoms

On SM120 (Blackwell RTX PRO 6000 / RTX 5090) with high concurrency (64+ simultaneous requests in SGLang with TP=8):
- CUTLASS FP4 GEMM intermittently fails to write output tiles
- Unwritten tiles contain uninitialized memory (NaN/garbage)
- NaN blocks are always contiguous and 128-aligned, matching CTA tile boundaries
- `CUDA_LAUNCH_BLOCKING=1` eliminates the bug (confirms race condition)
- cudnn backend is unaffected (does not use CUTLASS PDL)
- Retry with identical inputs produces correct output

## Fix

Add `-DCUTLASS_ENABLE_GDC_FOR_SM100=1` and `-DCUTLASS_ENABLE_GDC_FOR_SM90=1` to all affected GEMM JIT modules:
- `fp4_gemm_cutlass` (SM100)
- `fp4_gemm_cutlass_sm103` (SM103)
- `fp4_gemm_cutlass_sm120` (SM120)
- `fp8_gemm_cutlass` (SM100)
- `mxfp8_gemm_cutlass` (SM100)
- `gemm_sm120` (SM120 FP8 groupwise)

The `tgv_gemm` module already had `DCUTLASS_ENABLE_GDC_FOR_SM100`.

Note: `DCUTLASS_ENABLE_GDC_FOR_SM90` is needed because the SM120 CUTLASS kernel (`sm120_gemm_tma_warpspecialized_cooperative_asymmetric_dma.hpp`) guards `launch_dependent_grids()` with `#ifdef CUTLASS_ENABLE_GDC_FOR_SM90` instead of `SM100` (upstream CUTLASS bug).

## Verification

| Configuration | Result |
|---|---|
| PDL=true, no GDC flags (current) | **NaN crash** under high concurrency |
| PDL=false (workaround) | OK |
| PDL=true + GDC flags (this PR) | **OK** — tested with 64 concurrent requests, multiple SGLang restarts from JIT cache |
| `CUDA_LAUNCH_BLOCKING=1` | OK (confirms race condition) |

## Environment

- Hardware: 8x NVIDIA RTX PRO 6000 Blackwell (SM120, 96GB)
- FlashInfer 0.6.4, CUTLASS 4.4.1
- SGLang with TP=8, EAGLE-v2, GLM-5-NVFP4-MTP model
- PyTorch 2.12.0.dev, CUDA 12.8+

## Related

- #2708
- https://github.com/sgl-project/sglang/issues/20043
- https://github.com/sgl-project/sglang/pull/20047

## Release Notes

**Chores**
- Updated CUDA compilation configuration for SM100 and SM90 GPU architectures, enhancing build optimization and extending hardware compatibility for GPU acceleration workloads.

### CODE REVIEW

**Comment by johnnynunez** [comment]
Reported! Thanks

**Comment by aleozlx** [comment]
this PR seem to affect AOT package for 0.6.6 release
https://github.com/flashinfer-ai/flashinfer/actions/runs/22870567870/job/66353637447?pr=2730

**Comment by aleozlx** [comment]
btw have we filed an issue to cutlass?

**Comment by johnnynunez** [comment]
> btw have we filed an issue to cutlass?

@depaulmillz PR is the correct one, he is from cutlass team... I pinged him because the vLLM team pinged us and it was related with cutlass

**Comment by eugr** [comment]
@voipmonitor  -  Looks like this PR causes flashinfer-jit-cache compilation to fail if the build doesn't include SM90 arch, e.g. if we build with FLASHINFER_CUDA_ARCH_LIST=12.1a:

lots of errors like this. 

```
/workspace/flashinfer/build/aot/generated/gen_gemm_sm120/gemm_groupwise_e5m2_f16_majorfalse_sm120.cu -o /workspace/flashinfer/build/aot/cached_ops/gemm_sm120/gemm_groupwise_e5m2_f16_majorfalse_sm120.cuda.o
2026-03-10T15:07:27.044869Z 01E 2026-03-10 08:07:27,044 - INFO - #15 975.0 /workspace/flashinfer/3rdparty/cutlass/include/cutlass/gemm/kernel/sm90_gemm_tma_warpspecialized_cooperative.hpp(794): error: class "cutlass::gemm::kernel::detail::PersistentTileSchedulerSm100<cute::tuple<cute::_1, cute::_1, cute::_1>, 2U>" has no member "is_last_tile"
2026-03-10T15:07:27.044870Z 01E 2026-03-10 08:07:27,044 - INFO - #15 975.0           if (scheduler.is_last_tile(work_tile_info)) {
2026-03-10T15:07:27.044871Z 01E 2026-03-10 08:07:27,044 - INFO - #15 975.0                         ^
2026-03-10T15:07:27.044875Z 01E 2026-03-10 08:07:27,044 - INFO - #15 975.0           detected during:
2026-03-10T15:07:27.044876Z 01E 2026-03-10 08:07:27,044 - INFO - #15 975.0             instantiation of "void cutlass::gemm::kernel::GemmUniversal<ProblemShape_, CollectiveMainloop_, CollectiveEpilogue_, TileSchedulerTag_, std::enable_if_t<std::is_base_of_v<cutlass::gemm::KernelTmaWarpSpecializedCooperative, CollectiveMainloop_::DispatchPolicy::Schedule>, void>>::operator()(const cutlass::gemm::kernel::GemmUniversal<ProblemShape_, CollectiveMainloop_, CollectiveEpilogue_, TileSchedulerTag_, std::enable_if_t<std::is_base_of_v<cutlass::gemm::KernelTmaWarpSpecializedCooperative, CollectiveMainloop_::DispatchPolicy::Schedule>, void>>::Params &, char *) [with ProblemShape_=cute::tuple<int, int, int, int>, CollectiveMainloop_=cutlass::gemm::collective::CollectiveMma<cutlass::gemm::MainloopSm120TmaWarpSpecializedBlockwiseScaling<2, 2, cute::tuple<cute::_1, cute::_1, cute::_1>, cutlass::gemm::KernelTmaWarpSpecializedCooperativeBlockwiseScalingSm120<2>>, cute::tuple<cute::_128, cute::_128, cute::_128>, cutlass::float_e5m2_t, cute::tuple<cute::tuple<int64_t, cute::C<1>, int64_t>, cute::Layout<cute::tuple<cute::tuple<cute::C<1>, int32_t>, cute::tuple<cute::C<128>, int32_t>, int32_t>, cute::tuple<cute::tuple<cute::C<0>, cute::C<1>>, cute::tuple<cute::_0, int32_t>, int32_t>>>, cutlass::float_e5m2_t, cute::tuple<cute::tuple<int64_t, cute::C<1>, int64_t>, cute::Layout<cute::tuple<cute::tuple<cute::C<128>, int32_t>, cute::tuple<cute::C<128>, int32_t>, int32_t>, cute::tuple<cute::tuple<cute::C<0>, cute::C<1>>, cute::tuple<cute::_0, int32_t>, int32_t>>>, cute::TiledMMA<cute::MMA_Atom<cute::SM120_16x8x32_TN<cutlass::float_e5m2_t, cutlass::float_e5m2_t, float>>, cute::Layout<cute::tuple<cute::_4, cute::_2, cute::_1>, cute::tuple<cute::_1, cute::_4, cute::C<0>>>, cute::tuple<cute::C<128>, cute::C<32>, cute::_32>>, cute::SM90_TMA_LOAD, cute::ComposedLayout<cute::Swizzle<3, 4, 3>, cute::smem_ptr_flag_bits<8>, cute::Layout<cute::tuple<cute::_8, cute::_128>, cute::tuple<cute::_128, cute::_1>>>, cute::Copy_Atom<cute::SM75_U32x4_LDSM_N, uint8_t>, cute::identity, cute::SM90_TMA_LOAD, cute::ComposedLayout<cute::Swizzle<3, 4, 3>, cute::smem_ptr_flag_bits<8>, cute::Layout<cute::tuple<cute::_8, cute::_128>, cute::tuple<cute::_128, cute::_1>>>, cute::Copy_Atom<cute::SM75_U32x4_LDSM_N, uint8_t>, cute::identity>, CollectiveEpilogue_=cutlass::epilogue::collective::CollectiveEpilogue<cutlass::epilogue::Sm90TmaWarpSpecialized<3, 2, 4, true, false>, cute::tuple<cute::_128, cute::_128, cute::_128>, cute::tuple<cute::C<64>, cute::C<32>>, cutlass::half_t, cute::tuple<int64_t, cute::C<1>, int64_t>, cutlass::half_t, cute::tuple<int64_t, cute::C<1>, int64_t>, cutlass::epilogue::fusion::FusionCallbacks<cutlass::epilogue::Sm120TmaWarpSpecialized<3, 2, 4, true, false>, cutlass::epilogue::fusion::LinearCombination<cutlass::half_t, float, cutlass::half_t, float, cutlass::FloatRoundStyle::round_to_nearest>, cute::tuple<cute::_128, cute::_128, cute::_128>, cute::tuple<cute::C<64>, cute::C<32>>>, cute::SM90_TMA_LOAD, cute::ComposedLayout<cute::Swizzle<2, 4, 3>, cute::smem_ptr_flag_bits<16>, cute::Layout<cute::tuple<cute::C<8>, cute::C<32>>, cute::tuple<cute::_32, cute::_1>>>, cute::SM75_U32x2_LDSM_N, cute::SM90_TMA_STORE, cute::ComposedLayout<cute::Swizzle<2, 4, 3>, cute::smem_ptr_flag_bits<16>, cute::Layout<cute::tuple<cute::C<8>, cute::C<32>>, cute::tuple<cute::_32, cute::_1>>>, cute::SM90_U32x2_STSM_N, cute::Copy_Atom<cute::SM90_U32x2_STSM_N, cutlass::half_t>, void>, TileSchedulerTag_=void]" at line 123 of /workspace/flashinfer/3rdparty/cutlass/include/cutlass/device_kernel.h
```

@johnnynunez, @yzh119  - FYI
