### ISSUE TITLE
JIT Compilation Fails with "identifier 'entry' is undefined" When Enabling Profiler

### ISSUE THREAD

**Issue by ziyuhuang123** [flashinfer-ai/flashinfer#995]
# JIT Compilation Fails with "identifier 'entry' is undefined" When Enabling Profiler

## Environment

- **OS/Environment:** Conda environment (Python 3.10) on Linux  
- **CUDA Toolkit:** CUDA located at `/root/cuda/bin/nvcc`  
- **FlashInfer Installation:** Installed from source in development mode using `pip install -e .`  
- **Command Used:**  
  ```bash
  python mla.py --batch-size 64 --seq-len 1024 --num-heads 128 --profiler-buffer-size 1048576
  ```

## Reproduction Steps

1. **Clone the Repository and Update Submodules:**
   ```bash
   git clone https://github.com/flashinfer-ai/flashinfer.git --recursive
   cd flashinfer
   git submodule update --init --recursive
   ```

2. **Install in Development Mode:**
   ```bash
   pip install -e . -v
   ```

3. **Navigate to the Profiler Directory and Run the Script:**
   ```bash
   cd profiler
   python mla.py --batch-size 64 --seq-len 1024 --num-heads 128 --profiler-buffer-size 1048576
   ```

## Error Log

The build process begins by loading the JIT backend and then proceeds to compile the CUDA extension. Relevant excerpts from the error output are shown below:

```
2025-04-02 18:40:58,096 - INFO - flashinfer.jit: Prebuilt kernels not found, using JIT backend
2025-04-02 18:40:58,364 - INFO - flashinfer.jit: Loading JIT ops: batch_mla_attention_dtype_q_f16_dtype_kv_f16_dtype_o_f16_dtype_idx_i32_head_dim_ckv_512_head_dim_kpe_64_profiler_True_sm90
...
/root/miniconda3/envs/hzy_torch/lib/python3.10/site-packages/torch/utils/cpp_extension.py:1964: UserWarning: TORCH_CUDA_ARCH_LIST is not set, all archs for visible cards are included for compilation.
  warnings.warn(
...
RuntimeError: Error building extension 'batch_mla_attention_dtype_q_f16_dtype_kv_f16_dtype_o_f16_dtype_idx_i32_head_dim_ckv_512_head_dim_kpe_64_profiler_True_sm90':
...
/root/zyhuang/flashinfer/flashinfer/data/include/flashinfer/attention/mla_hopper.cuh(902): error: identifier "entry" is undefined
...
/root/zyhuang/flashinfer/flashinfer/data/include/flashinfer/attention/mla_hopper.cuh(912): error: identifier "entry" is undefined
...
```

## Issue Details

- **File Affected:**  
  `flashinfer/flashinfer/data/include/flashinfer/attention/mla_hopper.cuh` at lines around 902 and 912.

- **Problem:**  
  The compiler reports that the identifier `entry` is undefined when attempting to assign values to its members (e.g., `entry.tag` and `entry.delta_time`). It appears that in the profiler-related code (enabled by the `-DFLASHINFER_ENABLE_PROFILER` flag), the variable `entry` is used without being declared.

Any assistance or guidance to resolve this compilation error would be greatly appreciated.

**Comment by yzh119** [comment]
The profiler was broken in #952 , I'll add it back thank you for brining this up.
