### PR TITLE
fix(jit): enable GDC for CUTLASS GEMM PDL — SM100 flag only

### PR DESCRIPTION
**Pull request by voipmonitor**
## Summary

Re-applies #2716 (reverted in #2737) with the fix for the AOT build failure.

**Only `-DCUTLASS_ENABLE_GDC_FOR_SM100=1`** is added. The `-DCUTLASS_ENABLE_GDC_FOR_SM90=1` flag that broke AOT builds is intentionally omitted.

## Why the original PR broke AOT

`sm90_gemm_tma_warpspecialized_cooperative.hpp:794` has a direct `#ifdef CUTLASS_ENABLE_GDC_FOR_SM90` guard (not `CUTLASS_GDC_ENABLED`) that calls `scheduler.is_last_tile()`. When compiling SM120 kernels with that flag, the SM120 scheduler (`PersistentTileSchedulerSm100StreamK`) doesn't have `is_last_tile()` → compilation error.

## Why SM100 flag alone is sufficient

CUTLASS 4.2.1 `grid_dependency_control.h` defines `CUTLASS_GDC_ENABLED` for the entire SM100 family (SM100/101/103/120/121) when `CUTLASS_ENABLE_GDC_FOR_SM100` is set. This enables `griddepcontrol.wait` and `griddepcontrol.launch_dependents` device-side barriers for all affected architectures.

## Why this is needed

All affected GEMM kernels hardcode `enablePDL=true`, which enables host-side kernel overlap. Without the GDC compile flag, the device-side synchronization barriers compile as no-ops → race condition → NaN/garbage output tiles under concurrency.

## Affected modules

- `fp4_gemm_cutlass` (SM100)
- `fp4_gemm_cutlass_sm103` (SM103)
- `fp4_gemm_cutlass_sm120` (SM120)
- `fp8_gemm_cutlass` (SM100)
- `mxfp8_gemm_cutlass` (SM100)
- `gemm_sm120` (SM120 FP8 groupwise)

(`tgv_gemm` already had the SM100 flag.)

## Test plan

- [ ] AOT build with `FLASHINFER_CUDA_ARCH_LIST="12.1a"` (the exact config that broke before)
- [ ] AOT build with full arch list `"7.5 8.0 8.9 9.0a 10.0a 12.0a"`
- [ ] FP4 GEMM correctness under concurrent streams on SM120

🤖 Generated with [Claude Code](https://claude.com/claude-code)

## Summary by CodeRabbit

* **Chores**
  * Updated CUDA compilation configurations for matrix multiplication kernels across multiple data format variants (FP4, FP8, MXFP8, BF16) supporting additional GPU architectures.

### CODE REVIEW

**Comment by voipmonitor** [comment]
@johnnynunez  @aleozlx @bkryu can you please check

**Comment by yzh119** [comment]
I remember we have tried this but it still doesn't work. cc @aleozlx for confirmation.

**Comment by aleozlx** [comment]
now that we merged the cutlass bump, this may work now

https://github.com/flashinfer-ai/flashinfer/pull/2798

**Comment by aleozlx** [comment]
manually started spark test from the above . stand by as we wait on this result

**Comment by aleozlx** [comment]
https://gitlab-master.nvidia.com/dl/flashinfer/flashinfer-ci/-/jobs/284735560

**Comment by RobTand** [comment]
Confirming this fixes the race condition during CUDA graph capture on DGX Spark (SM121). I've been using `FLASHINFER_EXTRA_CUDAFLAGS="-DCUTLASS_ENABLE_GDC_FOR_SM100=1"` as a build-time workaround — this PR is the proper fix. Running NVFP4 MoE models (Nemotron-3-Super, Qwen3.5-122B) in production.

**Comment by aleozlx** [comment]
tests are clean

approved. merging is pending on the remaining CI run, eta this afternoon
