### PR TITLE
Normalize modular attention to CUTLASS DSL APIs shipped on PyPI

### LINKED ISSUE #3071: [Bug]tests/attention/test_modular_fmha_prefill.py failed of AttributeError: module 'cutlass.cute.arch' has no attribute 'ProxyKind'
Found this issue in nightly unit-test. [https://gitlab-master.nvidia.com/dl/flashinfer/flashinfer-ci/-/pipelines/48484614](https://gitlab-master.nvidia.com/dl/flashinfer/flashinfer-ci/-/pipelines/48484614)
Failed job example: https://gitlab-master.nvidia.com/dl/flashinfer/flashinfer-ci/-/jobs/297753421/raw
```
026-04-14T09:41:33.493300Z 01O =========================== short test summary info ============================
2026-04-14T09:41:33.493310Z 01O FAILED tests/attention/test_modular_fmha_prefill.py::test_attention_prefill[False-8-1-64-64] - AttributeError: module 'cutlass.cute.arch' has no attribute 'ProxyKind'
2026-04-14T09:41:33.493320Z 01O FAILED tests/attention/test_modular_fmha_prefill.py::test_attention_prefill[False-8-1-128-128] - AttributeError: module 'cutlass.cute.arch' has no attribute 'ProxyKind'
```
  - Commit 00ac5053 (https://github.com/flashinfer-ai/flashinfer/pull/2805) added code in correction.py that uses cute.arch.ProxyKind
 For example: 
 flashinfer/cute_dsl/attention/roles/correction.py:267
```
  cute.arch.fence_proxy(
      cute.arch.ProxyKind.async_shared,
      space=cute.arch.SharedSpace.shared_cta,
  )
```

  flashinfer/cute_dsl/attention/roles/softmax.py:448 has the same usage.

  Both calls pass cute.arch.ProxyKind.async_shared to cute.arch.fence_proxy, but ProxyKind is not exported from cutlass.cute.arch in the nvidia-cutlass-dsl 4.4.2 available on PyPI.

  This suggests the author of 00ac5053 developed against a build of nvidia-cutlass-dsl that differs from the published 4.4.2 on PyPI. A possible short-term workaround would be to check whether fence_proxy accepts a plain string (e.g. "async.shared") instead of the enum. The PR author should also clarify which exact version/build they tested against.

### PR DESCRIPTION
**Pull request by saltyminty**
## 📌 Description

Updated modular attention call sites to prefer the current CUTLASS DSL APIs while preserving backward-compatible fallbacks in the compat layer. Use the existing `setmaxregister_*` compatibility path in `flashinfer/cute_dsl/attention/compat.py', and add compatibility layer for `fence_proxy_async_shared_cta`, `exp2_fast`, and `make_rmem_tensor.`

Fixes the modular FMHA prefill failure reported in #3071: `AttributeError: module 'cutlass.cute.arch' has no attribute 'ProxyKind'`.

## 🔍 Related Issues

https://github.com/flashinfer-ai/flashinfer/issues/3071

## 🚀 Pull Request Checklist

Thank you for contributing to FlashInfer! Before we review your pull request, please make sure the following items are complete.

### ✅ Pre-commit Checks

- [ ] I have installed `pre-commit` by running `pip install pre-commit` (or used your preferred method).
- [ ] I have installed the hooks with `pre-commit install`.
- [ ] I have run the hooks manually with `pre-commit run --all-files` and fixed any reported issues.

> If you are unsure about how to set up `pre-commit`, see [the pre-commit documentation](https://pre-commit.com/).

## 🧪 Tests

- [ ] Tests have been added or updated as needed.
- [ ] All tests are passing (`unittest`, etc.).

## Summary by CodeRabbit

* **Refactor**
  * Introduced compatibility wrappers for low-level GPU primitives to standardize exponentiation, tensor/register creation, and synchronization across environments.
  * Updated attention kernels to use these wrappers, improving consistency of math and memory/register handling.
  * Improved register budgeting and synchronization behavior in the kernel execution pipeline for more reliable performance.

### CODE REVIEW

**Review by aleozlx — APPROVED** [review]

**Comment by saltyminty** [comment]
Duplicate
