### ISSUE TITLE
C++ compilation error

### ISSUE THREAD

**Issue by binhtranmcs** [flashinfer-ai/flashinfer#674]
I tried running benchmark code as guided [here](https://docs.flashinfer.ai/installation.html#c-api), but it throws error:
```
Could NOT find IBVerbs (missing: IBVERBS_LIBRARIES)
```
I tried removing the `find_package(IBVerbs REQUIRED)` in `mscclpp/CMakeLists.txt` and rebuilt, but it still throws error:
```
The dependency target "dispatch_inc" of target "bench_single_decode" does not exist.
```
It seems that `dispatch.inc` is missing. I think the docs for C++ is very much outdated. Please help me with this. Thanks in advance!

**Comment by yzh119** [comment]
Yeah CMakeLists was broken in https://github.com/flashinfer-ai/flashinfer/pull/643, will fix it later.

**Comment by ByronHsu** [comment]
same here

**Comment by binhtranmcs** [comment]
#678 fixes the issue. Thanks all.
